batch_size: 32
epochs: 40
model_name: rnn
random_state: 42
train_set_size: 0.6
val_set_size: 0.2
data_dir: data
model_structure:
  n_layers: 4
  d_model: 128
  max_pos_encoding: 2048
  init_learning_rate: 0.001
  dropout_rate: 0.2
  activations: [selu, sigmoid]
training:
  monitor: val_loss
  monitor_mode: min
  save_best_weights: True
  lr_reducing:
    monitor: val_loss
    patience: 20
    min_lr: 1.e-7
    mode: min