train_set_size: 0.7
val_set_size: 0.15
random_state: 420
name: wav2vec2-base
pretrained_feature_extractor: facebook/wav2vec2-base
pretrained_transformer_classificator: facebook/wav2vec2-base
transformer_name: music_tagging_transformer_exp
output_dir: models/huggingface
training:
  eval_strategy: epoch
  save_strategy: epoch
  learning_rate: 3.e-4
  train_batch_size: 32
  eval_batch_size: 32
  gradient_accumulation_steps: 4
  num_train_epochs: 20
  warmup_ratio: 0.1
  logging_steps: 5
  load_best_model_at_end: True
  metric_for_best_model: eval_accuracy
  early_stopping_patience: 4
