
train_size: 0.7
val_size: 0.15
model_name: sccnn
output_dir: models/sccnn
batch_size: 32
epochs: 50
random_state: 420
model_structure:
  layers:
    - [conv2D, 8, 3, relu]
    - [maxpool2D, 4]
    - [conv2D, 16, 3, relu]
    - [maxpool2D, 4]
    - [conv2D, 32, 3, relu]
    - [maxpool2D, 4]
    - [conv2D, 64, 3, relu]
    - [maxpool2D, 4]
    - [conv2D, 64, 3, relu]
  dense_size: 32
training:
  monitor: val_loss
  monitor_mode: min
  save_best_weights: True
  lr_reducing:
    monitor: val_loss
    patience: 3
    min_lr: 1.e-7
    mode: min
  early_stopping:
    patience: 8
    monitor: val_loss
    restore_best_weights: True